/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.SaleLineDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DTO representing a purchase ticket
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-02T11:37:30.291+02:00[Europe/Paris]")
public class TicketDTO {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_SALE_LINES = "saleLines";
  @SerializedName(SERIALIZED_NAME_SALE_LINES)
  private List<SaleLineDTO> saleLines = new ArrayList<>();

  public TicketDTO() {
  }

  public TicketDTO id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Unique ticket ID
   * @return id
  **/
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public TicketDTO saleLines(List<SaleLineDTO> saleLines) {
    
    this.saleLines = saleLines;
    return this;
  }

  public TicketDTO addSaleLinesItem(SaleLineDTO saleLinesItem) {
    if (this.saleLines == null) {
      this.saleLines = new ArrayList<>();
    }
    this.saleLines.add(saleLinesItem);
    return this;
  }

   /**
   * List of sale lines included in the ticket
   * @return saleLines
  **/
  @javax.annotation.Nonnull
  public List<SaleLineDTO> getSaleLines() {
    return saleLines;
  }


  public void setSaleLines(List<SaleLineDTO> saleLines) {
    this.saleLines = saleLines;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketDTO comComerzziaPromocionesapiDtoTicketDTO = (TicketDTO) o;
    return Objects.equals(this.id, comComerzziaPromocionesapiDtoTicketDTO.id) &&
        Objects.equals(this.saleLines, comComerzziaPromocionesapiDtoTicketDTO.saleLines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, saleLines);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComComerzziaPromocionesapiDtoTicketDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    saleLines: ").append(toIndentedString(saleLines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("saleLines");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("saleLines");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ComComerzziaPromocionesapiDtoTicketDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TicketDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ComComerzziaPromocionesapiDtoTicketDTO is not found in the empty JSON string", TicketDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!TicketDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ComComerzziaPromocionesapiDtoTicketDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TicketDTO.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("saleLines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `saleLines` to be an array in the JSON string but got `%s`", jsonObj.get("saleLines").toString()));
      }

      JsonArray jsonArraysaleLines = jsonObj.getAsJsonArray("saleLines");
      // validate the required field `saleLines` (array)
      for (int i = 0; i < jsonArraysaleLines.size(); i++) {
        SaleLineDTO.validateJsonObject(jsonArraysaleLines.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TicketDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ComComerzziaPromocionesapiDtoTicketDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TicketDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TicketDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<TicketDTO>() {
           @Override
           public void write(JsonWriter out, TicketDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TicketDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ComComerzziaPromocionesapiDtoTicketDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ComComerzziaPromocionesapiDtoTicketDTO
  * @throws IOException if the JSON string is invalid with respect to ComComerzziaPromocionesapiDtoTicketDTO
  */
  public static TicketDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TicketDTO.class);
  }

 /**
  * Convert an instance of ComComerzziaPromocionesapiDtoTicketDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

