/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LineaVenta
 */
public class LineaVentaTest {
    private final LineaVenta model = new LineaVenta();

    /**
     * Model tests for LineaVenta
     */
    @Test
    public void testLineaVenta() {
        // TODO: test LineaVenta
    }

    /**
     * Test the property 'codigoArticulo'
     */
    @Test
    public void codigoArticuloTest() {
        // TODO: test codigoArticulo
    }

    /**
     * Test the property 'cantidad'
     */
    @Test
    public void cantidadTest() {
        // TODO: test cantidad
    }

    /**
     * Test the property 'precioUnitarioOriginal'
     */
    @Test
    public void precioUnitarioOriginalTest() {
        // TODO: test precioUnitarioOriginal
    }

    /**
     * Test the property 'precioUnitarioPromocionado'
     */
    @Test
    public void precioUnitarioPromocionadoTest() {
        // TODO: test precioUnitarioPromocionado
    }

    /**
     * Test the property 'importeTotal'
     */
    @Test
    public void importeTotalTest() {
        // TODO: test importeTotal
    }

    /**
     * Test the property 'idPromocionAplicada'
     */
    @Test
    public void idPromocionAplicadaTest() {
        // TODO: test idPromocionAplicada
    }

}
