/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PromocionEntity
 */
public class PromocionEntityTest {
    private final PromocionEntity model = new PromocionEntity();

    /**
     * Model tests for PromocionEntity
     */
    @Test
    public void testPromocionEntity() {
        // TODO: test PromocionEntity
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descripcion'
     */
    @Test
    public void descripcionTest() {
        // TODO: test descripcion
    }

    /**
     * Test the property 'fechaAlta'
     */
    @Test
    public void fechaAltaTest() {
        // TODO: test fechaAlta
    }

    /**
     * Test the property 'fechaInicio'
     */
    @Test
    public void fechaInicioTest() {
        // TODO: test fechaInicio
    }

    /**
     * Test the property 'fechaFin'
     */
    @Test
    public void fechaFinTest() {
        // TODO: test fechaFin
    }

    /**
     * Test the property 'codigoArticulo'
     */
    @Test
    public void codigoArticuloTest() {
        // TODO: test codigoArticulo
    }

    /**
     * Test the property 'tipo'
     */
    @Test
    public void tipoTest() {
        // TODO: test tipo
    }

    /**
     * Test the property 'precioPromocion'
     */
    @Test
    public void precioPromocionTest() {
        // TODO: test precioPromocion
    }

    /**
     * Test the property 'porcentajeDescuento'
     */
    @Test
    public void porcentajeDescuentoTest() {
        // TODO: test porcentajeDescuento
    }

}
