/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ComComerzziaPromocionesapiDtoFixedPriceDetails
 */
public class FixedPriceDetailsTest {
    private final FixedPriceDetails model = new FixedPriceDetails();

    /**
     * Model tests for ComComerzziaPromocionesapiDtoFixedPriceDetails
     */
    @Test
    public void testComComerzziaPromocionesapiDtoFixedPriceDetails() {
        // TODO: test ComComerzziaPromocionesapiDtoFixedPriceDetails
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

}
