/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.client.model.DiscountDetails;
import org.openapitools.client.model.FixedPriceDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ComComerzziaPromocionesapiDtoPromotionDTO
 */
public class PromotionDTOTest {
    private final PromotionDTO model = new PromotionDTO();

    /**
     * Model tests for ComComerzziaPromocionesapiDtoPromotionDTO
     */
    @Test
    public void testComComerzziaPromocionesapiDtoPromotionDTO() {
        // TODO: test ComComerzziaPromocionesapiDtoPromotionDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'itemCode'
     */
    @Test
    public void itemCodeTest() {
        // TODO: test itemCode
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'discountDetails'
     */
    @Test
    public void discountDetailsTest() {
        // TODO: test discountDetails
    }

    /**
     * Test the property 'fixedPriceDetails'
     */
    @Test
    public void fixedPriceDetailsTest() {
        // TODO: test fixedPriceDetails
    }

    /**
     * Test the property 'validPromotion'
     */
    @Test
    public void validPromotionTest() {
        // TODO: test validPromotion
    }

}
