/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ComComerzziaPromocionesapiDtoSaleLineDTO
 */
public class SaleLineDTOTest {
    private final SaleLineDTO model = new SaleLineDTO();

    /**
     * Model tests for ComComerzziaPromocionesapiDtoSaleLineDTO
     */
    @Test
    public void testComComerzziaPromocionesapiDtoSaleLineDTO() {
        // TODO: test ComComerzziaPromocionesapiDtoSaleLineDTO
    }

    /**
     * Test the property 'itemCode'
     */
    @Test
    public void itemCodeTest() {
        // TODO: test itemCode
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'originalUnitPrice'
     */
    @Test
    public void originalUnitPriceTest() {
        // TODO: test originalUnitPrice
    }

    /**
     * Test the property 'discountedUnitPrice'
     */
    @Test
    public void discountedUnitPriceTest() {
        // TODO: test discountedUnitPrice
    }

    /**
     * Test the property 'totalAmount'
     */
    @Test
    public void totalAmountTest() {
        // TODO: test totalAmount
    }

    /**
     * Test the property 'appliedPromotionId'
     */
    @Test
    public void appliedPromotionIdTest() {
        // TODO: test appliedPromotionId
    }

}
