/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.SaleLineDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ComComerzziaPromocionesapiDtoTicketDTO
 */
public class TicketDTOTest {
    private final TicketDTO model = new TicketDTO();

    /**
     * Model tests for ComComerzziaPromocionesapiDtoTicketDTO
     */
    @Test
    public void testComComerzziaPromocionesapiDtoTicketDTO() {
        // TODO: test ComComerzziaPromocionesapiDtoTicketDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'saleLines'
     */
    @Test
    public void saleLinesTest() {
        // TODO: test saleLines
    }

}
